using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using LSLIBWebBased;
using System.Data;


public partial class Config_Company : System.Web.UI.Page
{
    protected ClassHashTableHelper ClsHashTableHelper;
    protected ClassFileUploadHelper ClsFileUploadHelper = new ClassFileUploadHelper();
    
    //查询内容类型
    private string msContentType
    {
        get
        {
            if (LSLIBWebBased.nsSQL.mSQL.oHandleNullAndNothing(this.Request.QueryString["ContenType"]) == null)
            {
                return "Contentype";
            }
            else
            {
                return this.Request.QueryString["ContentType"];
            }
        }
    }

    protected void Page_Init(object sender, EventArgs e)
    {
        //檢查登入權限+取得翻譯表
        LSLIBWebBased.nsClass.mClass.cPageLoadHelper_GuocoWeb(this, ref ClsHashTableHelper, true, "", "", true);

        this.Title = ClsHashTableHelper.sGetHash(ClsHashTableHelper.mClassMyConfiguration.msPostCode);
        this.ucPageHeader1.msTitle = this.Title;
        //this.lblReportName.Text = this.Title;
        
        LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);
       
    }

    protected void Page_Load(object sender, EventArgs e)
    {
       // LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);
        //LSLIBWebBased.nsCommon.mCommon.fTextBoxSetEnterEvent(this.txtSearchKey, btnSearch);

        if (!IsPostBack)
        {
            txtRemark.Attributes.Add("MaxLength", txtRemark.MaxLength.ToString());

            this.divCoverLayer.Visible = false;
            this.divPopUpPanel.Visible = false;

            LIBLocal.BindDDLUserList(ddl2ndApprover, ClsHashTableHelper.mClassMyConfiguration.msSystemCode, "Config_Company_2Approver", "", "");
            ddl2ndApprover.Items.Insert(0, "");

            LIBLocal.BindDDLUserList(ddl3rdApprover, ClsHashTableHelper.mClassMyConfiguration.msSystemCode, "Config_Company_3Approver", "", "");
            ddl3rdApprover.Items.Insert(0, "");

            LIBLocal.BindDDLUserList(ddl4thApprover, ClsHashTableHelper.mClassMyConfiguration.msSystemCode, "Config_Company_4Approver", "", "");
            ddl4thApprover.Items.Insert(0, "");
          
            //this.txtSearchKey.Text = lblInvoiceNum.Text;

            //LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btnExcelUpload_header, "ExcelUpload.aspx?UploadType=TAX_ReconciliationTracking_Header");
          
            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLStatus", ddlInfoStatus_edit, LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);
                       
            FillGridViewAll();
        }
    }


    private object FillGridViewAll()
    {
        FillGridView1();

        return null;
    }

    private object FillGridView1()
    {
        LSLIBWebBased.ClassLoadFieldHelper ClsLoadFieldHelper = new LSLIBWebBased.ClassLoadFieldHelper();
        //ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@Search", this.txtSearchKey.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@action", "Search");
        ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Company_GridDetail");
        ClsLoadFieldHelper.fBindControls(GridView1);
        
        this.lblCountLabel1.Text = (string)ClsLoadFieldHelper.iRowCountDesc();
        LIBLocal.SetViewSQLScript(ClsLoadFieldHelper, this.ClsHashTableHelper, "N", lblPrintSql);
        return null;
    }


    //private object FillGridViewExcel()
    //{

    //    ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

    //    ClsLoadFieldHelper.fAddSqlParameter("@Search", this.lblSearch.Text);
    //    ClsLoadFieldHelper.fAddSqlParameter("@Project_Code", this.lblProjectCode.Text);
    //    ClsLoadFieldHelper.fAddSqlParameter("@Function_Name", this.lblFunctionName.Text);
    //    ClsLoadFieldHelper.fAddSqlParameter("@FGroup", this.lblFunctionGroupName.Text);
    //    ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Grid_SystemRightManagement_FGroupUserPrivilege");
    //    ClsLoadFieldHelper.fBindControls(GridView5);

    //    ClassLoadFieldHelper ClsLoadFieldHelper1 = new ClassLoadFieldHelper();

    //    ClsLoadFieldHelper1.fAddSqlParameter("@Search", this.lblSearch.Text);
    //    ClsLoadFieldHelper1.fAddSqlParameter("@Project_Code", this.lblProjectCode.Text);
    //    ClsLoadFieldHelper1.fAddSqlParameter("@Function_Name", this.lblFunctionName.Text);
    //    ClsLoadFieldHelper1.fAddSqlParameter("@FGroup", this.lblFunctionGroupName.Text);
    //    ClsLoadFieldHelper1.fBuildDataSet("stp_wf_all_Grid_SystemRightManagement_FunctionGroup");
    //    ClsLoadFieldHelper1.fBindControls(GridView6);

    //    return null;
    //}



    protected void btnSearch_Click(object sender, EventArgs e)
    {
        lblSearch.Text = this.txtSearchKey.Text;

        FillGridView1();
    }

    protected void GridView1_RowDataBound(object sender, System.Web.UI.WebControls.GridViewRowEventArgs e)
    {
        //foreach (GridViewRow row in GridView1.Rows)
        //{
        //    //Button lbtnMarkCloseInfo = (Button)row.FindControl("btnMarkCloseInfo");
        //    //lbtnMarkCloseInfo.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to mark close?") + "');";

        //    Button lbtnResetPassword = (Button)row.FindControl("btnResetPassword");
        //    lbtnResetPassword.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to reset user password?") + "');";

        //    //Button lbtnSendPassword = (Button)row.FindControl("btnSendPassword");
        //    //lbtnSendPassword.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to send user password?") + "');";
        //}
    }

   
    protected void GridView1_RowCommand(object sender, System.Web.UI.WebControls.GridViewCommandEventArgs e)
    {
        switch (e.CommandName)
        {

            case "Edit1":
                if (this.divCoverLayer.Visible == false)
                {
                    int index1 = Convert.ToInt32(e.CommandArgument);

                    int PageIndex = this.GridView1.PageIndex;
                    int PageSize = this.GridView1.PageSize;

                    index1 = index1 - PageIndex * PageSize;                                    

                     Label lLabel_Edit1 = this.GridView1.Rows[index1].FindControl("lblKey_Header") as Label;
                     string sKey_Edit1 = lLabel_Edit1.Text;

                     if (bCanHaveRight(sKey_Edit1, "Edit"))
                    {
                      this.Label6.Text = "Edit Company";
                      this.btnUpdate_Info.Text = "Edit";
                     // this.lblAction.Text = "Update";
                      this.divCoverLayer.Visible = true;
                      this.divPopUpPanel.Visible = true;
                      this.div_ProfileStatus_edit.Visible = true;
                     //this.btnGetNewField_Type.Visible = false;

                     //Label lLabel2_Edit1 = this.GridView1.Rows[index1].FindControl("lblKeyCustomerCompany_Header") as Label;
                     //string sCustomerCompany_Edit1 = lLabel2_Edit1.Text;

                     ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

                     ClsLoadFieldHelper.fAddSqlParameter("@Search", sKey_Edit1);
                     ClsLoadFieldHelper.fAddSqlParameter("@action", "Get");
                     ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Company_GridDetail");

                     this.txtCompanyCode.Text = sKey_Edit1;
                     this.txtCompanyCode.Enabled = false;
                     ClsLoadFieldHelper.LoadSqlField("CompanyShortName", ref  txtCompanyShortName);
                     ClsLoadFieldHelper.LoadSqlField("CompanyFullName", ref  txtCompanyFullName);
                     ClsLoadFieldHelper.LoadSqlField("Remark", ref  txtRemark);
                     ClsLoadFieldHelper.LoadSqlField("MinPasswordLength", ref  txtMinPasswordlength);
                     ClsLoadFieldHelper.LoadSqlField("Status", ref  ddlInfoStatus_edit);
                     ClsLoadFieldHelper.LoadSqlField("SecondApprover", ref  ddl2ndApprover);
                     ClsLoadFieldHelper.LoadSqlField("ThirdApprover", ref  ddl3rdApprover);
                     ClsLoadFieldHelper.LoadSqlField("ForthApprover", ref  ddl4thApprover);
                    }

                }
                break;
         
        }
    }


    protected void btnClose_Info_Click(object sender, EventArgs e)
    {
        this.divPopUpPanel.Visible = false;
        this.divCoverLayer.Visible = false;
       // FillGridView1();
        clearEditFields();
    }

    protected void btnInsert_AddCompany_Click(object sender, EventArgs e)
    {
        //this.lblAction.Text = "New";
        //this.txtID.Enabled = true;
        if (bCanHaveRight("", "Add"))
        {
            this.Label6.Text = "Add Company";
            this.btnUpdate_Info.Text = "Add";
            this.txtCompanyCode.Enabled = true;
            this.div_ProfileStatus_edit.Visible = false;
            this.divPopUpPanel.Visible = true;
            this.divCoverLayer.Visible = true;
        }
    }


    protected void btnUpdate_Info_Click(object sender, EventArgs e)
    {
        ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@CompanyCode", this.txtCompanyCode.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@CompanyShortName ", this.txtCompanyShortName.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@CompanyFullName", this.txtCompanyFullName.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Remark", this.txtRemark.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@MinPasswordLength", this.txtMinPasswordlength.Text);

        ClsLoadFieldHelper.fAddSqlParameter("@SecondApprover", this.ddl2ndApprover);
        ClsLoadFieldHelper.fAddSqlParameter("@ThirdApprover ", this.ddl3rdApprover);
        ClsLoadFieldHelper.fAddSqlParameter("@ForthApprover", this.ddl4thApprover);

        ClsLoadFieldHelper.fAddSqlParameter("@UpdateBy", this.ClsHashTableHelper.msUserName);


        if (this.txtCompanyCode.Enabled == true)
        {
            ClsLoadFieldHelper.fAddSqlParameter("@Status", "Active");
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Company_insert");
        }
        else
        {
            ClsLoadFieldHelper.fAddSqlParameter("@Status", this.ddlInfoStatus_edit.Text);
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Company_update");
        }

        if (ClsLoadFieldHelper.mbDataSetHasRecord)
        {
            //LSLIBWebBased.nsScript.mScript.Alert(this, ClsLoadFieldHelper.oLoadSqlField("Result").ToString(), false);
            lblAlert3.Visible = true;
            lblAlert3.Text = ClsLoadFieldHelper.oLoadSqlField("Result").ToString();
        }
        else
        {            
            FillGridView1();
            this.divPopUpPanel.Visible = false;
            this.divCoverLayer.Visible = false;
            clearEditFields();
        }
    }
    
    
    private object clearEditFields()
    {
        txtCompanyCode.Text = "";
        txtCompanyShortName.Text = "";
        txtCompanyFullName.Text = "";
        txtRemark.Text = "";
        txtMinPasswordlength.Text = "";
        ddlInfoStatus_edit.Text = "";

        ddl2ndApprover.Text = "";
        ddl3rdApprover.Text = "";
        ddl4thApprover.Text = "";

        lblAlert3.Visible = false;
        lblAlert3.Text = "";

        return null;
    }

    public bool bCanHaveRight(String psCompanyCode, String psAction)
    {
        ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@username", this.ClsHashTableHelper.msUserName);
        ClsLoadFieldHelper.fAddSqlParameter("@CompanyCode", psCompanyCode);
        ClsLoadFieldHelper.fAddSqlParameter("@Action", psAction);

        ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Company_bCanHaveRight");

        if (ClsLoadFieldHelper.mbDataSetHasRecord)
        {
            LSLIBWebBased.nsScript.mScript.Alert(this, ClsLoadFieldHelper.oLoadSqlField("Result").ToString(), false);
            return false;
        }
        else
        {
            return true;
        }
    }

    //protected void btnExporttoExcel_Click1(object sender, EventArgs e)
    //{
    //    //LSLIBWebBased.LIBWebBased.ExportToExcelMaster(this.GridView1, this, FillGridView1);
    //    LSLIBWebBased.LIBWebBased.ExportToExcelMaster(this.divDetail, this, FillGridViewExcel);

    //}
   
   
}