using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using LSLIBWebBased;
using System.Data;


public partial class Config_Division : System.Web.UI.Page
{
    protected ClassHashTableHelper ClsHashTableHelper;
    protected ClassFileUploadHelper ClsFileUploadHelper = new ClassFileUploadHelper();
    
    //查询内容类型
    private string msContentType
    {
        get
        {
            if (LSLIBWebBased.nsSQL.mSQL.oHandleNullAndNothing(this.Request.QueryString["ContenType"]) == null)
            {
                return "Contentype";
            }
            else
            {
                return this.Request.QueryString["ContentType"];
            }
        }
    }

    protected void Page_Init(object sender, EventArgs e)
    {
        //檢查登入權限+取得翻譯表
        LSLIBWebBased.nsClass.mClass.cPageLoadHelper_GuocoWeb(this, ref ClsHashTableHelper, true, "", "", true);

        this.Title = ClsHashTableHelper.sGetHash(ClsHashTableHelper.mClassMyConfiguration.msPostCode);
        this.ucPageHeader1.msTitle = this.Title;
        //this.lblReportName.Text = this.Title;
        
        LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);
       
    }

    protected void Page_Load(object sender, EventArgs e)
    {
       // LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);
        //LSLIBWebBased.nsCommon.mCommon.fTextBoxSetEnterEvent(this.txtSearchKey, btnSearch);

        if (!IsPostBack)
        {
            this.divCoverLayer.Visible = false;
            this.divPopUpPanel.Visible = false;
          
            //this.txtSearchKey.Text = lblInvoiceNum.Text;

            //LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btnExcelUpload_header, "ExcelUpload.aspx?UploadType=TAX_ReconciliationTracking_Header");

            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLCompanyCode", ddlCompanyCode, LSLIBWebBased.LIBWebBased.enDropDownListType.All);

            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLCompanyCode", ddlCompanyCode_edit, LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);
          
            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLStatus", ddlInfoStatus_edit, LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);

            FillGridView1();
        }
    }


    //private object FillGridViewAll()
    //{
    //    FillGridView1();
       
    //    return null;
    //}

    private object FillGridView1()
    {
        LSLIBWebBased.ClassLoadFieldHelper ClsLoadFieldHelper = new LSLIBWebBased.ClassLoadFieldHelper();
        //ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@CompanyCode", this.ddlCompanyCode.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Search", this.txtSearchKey.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@action", "Search");
        ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Division_GridDetail");
        ClsLoadFieldHelper.fBindControls(GridView1);
        
        this.lblCountLabel1.Text = (string)ClsLoadFieldHelper.iRowCountDesc();
        LIBLocal.SetViewSQLScript(ClsLoadFieldHelper, this.ClsHashTableHelper, "N", lblPrintSql);
        return null;
    }


    //private object FillGridViewExcel()
    //{

    //    ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

    //    ClsLoadFieldHelper.fAddSqlParameter("@Search", this.lblSearch.Text);
    //    ClsLoadFieldHelper.fAddSqlParameter("@Project_Code", this.lblProjectCode.Text);
    //    ClsLoadFieldHelper.fAddSqlParameter("@Function_Name", this.lblFunctionName.Text);
    //    ClsLoadFieldHelper.fAddSqlParameter("@FGroup", this.lblFunctionGroupName.Text);
    //    ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Grid_SystemRightManagement_FGroupUserPrivilege");
    //    ClsLoadFieldHelper.fBindControls(GridView5);

    //    ClassLoadFieldHelper ClsLoadFieldHelper1 = new ClassLoadFieldHelper();

    //    ClsLoadFieldHelper1.fAddSqlParameter("@Search", this.lblSearch.Text);
    //    ClsLoadFieldHelper1.fAddSqlParameter("@Project_Code", this.lblProjectCode.Text);
    //    ClsLoadFieldHelper1.fAddSqlParameter("@Function_Name", this.lblFunctionName.Text);
    //    ClsLoadFieldHelper1.fAddSqlParameter("@FGroup", this.lblFunctionGroupName.Text);
    //    ClsLoadFieldHelper1.fBuildDataSet("stp_wf_all_Grid_SystemRightManagement_FunctionGroup");
    //    ClsLoadFieldHelper1.fBindControls(GridView6);

    //    return null;
    //}



    protected void btnSearch_Click(object sender, EventArgs e)
    {
        lblSearch.Text = this.txtSearchKey.Text;

        FillGridView1();
    }

    protected void GridView1_RowDataBound(object sender, System.Web.UI.WebControls.GridViewRowEventArgs e)
    {
        //foreach (GridViewRow row in GridView1.Rows)
        //{
        //    //Button lbtnMarkCloseInfo = (Button)row.FindControl("btnMarkCloseInfo");
        //    //lbtnMarkCloseInfo.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to mark close?") + "');";

        //    Button lbtnResetPassword = (Button)row.FindControl("btnResetPassword");
        //    lbtnResetPassword.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to reset user password?") + "');";

        //    //Button lbtnSendPassword = (Button)row.FindControl("btnSendPassword");
        //    //lbtnSendPassword.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to send user password?") + "');";
        //}
    }

   
    protected void GridView1_RowCommand(object sender, System.Web.UI.WebControls.GridViewCommandEventArgs e)
    {
        switch (e.CommandName)
        {

            case "Edit1":
                if (this.divCoverLayer.Visible == false)
                {
                    int index1 = Convert.ToInt32(e.CommandArgument);

                    int PageIndex = this.GridView1.PageIndex;
                    int PageSize = this.GridView1.PageSize;

                    index1 = index1 - PageIndex * PageSize;                                    

                     Label lLabel_Edit1 = this.GridView1.Rows[index1].FindControl("lblKey_Header") as Label;
                     string sKey_Edit1 = lLabel_Edit1.Text;

                  
                      this.Label6.Text = "Edit Division";
                      this.btnUpdate_Info.Text = "Edit";
                     // this.lblAction.Text = "Update";
                      this.divCoverLayer.Visible = true;
                      this.divPopUpPanel.Visible = true;
                      this.div_ProfileStatus_edit.Visible = true;
                     //this.btnGetNewField_Type.Visible = false;

                     //Label lLabel2_Edit1 = this.GridView1.Rows[index1].FindControl("lblKeyCustomerCompany_Header") as Label;
                     //string sCustomerCompany_Edit1 = lLabel2_Edit1.Text;

                     ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

                     ClsLoadFieldHelper.fAddSqlParameter("@CompanyCode", this.ddlCompanyCode.Text);
                     ClsLoadFieldHelper.fAddSqlParameter("@Search", sKey_Edit1);
                     ClsLoadFieldHelper.fAddSqlParameter("@action", "Get");
                     ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Division_GridDetail");

                     this.txtDivisionCode.Text = sKey_Edit1;
                     this.txtDivisionCode.Enabled = false;
                     ClsLoadFieldHelper.LoadSqlField("DivisionShortName", ref  txtDivisionShortName);
                     ClsLoadFieldHelper.LoadSqlField("DivisionFullName", ref  txtDivisionFullName);
                     ClsLoadFieldHelper.LoadSqlField("CompanyCode", ref  ddlCompanyCode_edit);
                     ClsLoadFieldHelper.LoadSqlField("Remark", ref  txtRemark);
                     ClsLoadFieldHelper.LoadSqlField("Status", ref  ddlInfoStatus_edit);
                   
                }
                break;         
        }
    }


    protected void btnClose_Info_Click(object sender, EventArgs e)
    {
        this.divPopUpPanel.Visible = false;
        this.divCoverLayer.Visible = false;
       // FillGridView1();
        clearEditFields();
    }

    protected void btnInsert_AddDivision_Click(object sender, EventArgs e)
    {
        //this.lblAction.Text = "New";
        //this.txtID.Enabled = true;
        
        this.Label6.Text = "Add Division";
        this.btnUpdate_Info.Text = "Add";
        this.txtDivisionCode.Enabled = true;
        this.div_ProfileStatus_edit.Visible = false;
        this.divPopUpPanel.Visible = true;
        this.divCoverLayer.Visible = true;        
}


    protected void btnUpdate_Info_Click(object sender, EventArgs e)
    {
        ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@DivisionCode", this.txtDivisionCode.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@DivisionShortName ", this.txtDivisionShortName.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@DivisionFullName", this.txtDivisionFullName.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Remark", this.txtRemark.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@CompanyCode", this.ddlCompanyCode_edit.Text);

        ClsLoadFieldHelper.fAddSqlParameter("@UpdateBy", this.ClsHashTableHelper.msUserName);


        if (this.txtDivisionCode.Enabled == true)
        {
            ClsLoadFieldHelper.fAddSqlParameter("@Status", "Active");
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Division_insert");
        }
        else
        {
            ClsLoadFieldHelper.fAddSqlParameter("@Status", this.ddlInfoStatus_edit.Text);
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Config_Division_update");
        }

        if (ClsLoadFieldHelper.mbDataSetHasRecord)
        {
            //LSLIBWebBased.nsScript.mScript.Alert(this, ClsLoadFieldHelper.oLoadSqlField("Result").ToString(), false);
            lblAlert3.Visible = true;
            lblAlert3.Text = ClsLoadFieldHelper.oLoadSqlField("Result").ToString();
        }
        else
        {            
            FillGridView1();
            this.divPopUpPanel.Visible = false;
            this.divCoverLayer.Visible = false;
            clearEditFields();
        }
    }
    
    
    private object clearEditFields()
    {
        txtDivisionCode.Text = "";
        txtDivisionShortName.Text = "";
        txtDivisionFullName.Text = "";
        txtRemark.Text = "";
        ddlCompanyCode_edit.Text = "";
        ddlInfoStatus_edit.Text = "";

        lblAlert3.Visible = false;
        lblAlert3.Text = "";

        return null;
    }

   

    //protected void btnExporttoExcel_Click1(object sender, EventArgs e)
    //{
    //    //LSLIBWebBased.LIBWebBased.ExportToExcelMaster(this.GridView1, this, FillGridView1);
    //    LSLIBWebBased.LIBWebBased.ExportToExcelMaster(this.divDetail, this, FillGridViewExcel);

    //}
   
   
}