using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using LSLIBWebBased;
using System.Data;

public partial class Config_Privilege_UserSystemRights : System.Web.UI.Page
{
    protected ClassHashTableHelper ClsHashTableHelper;
    protected ClassFileUploadHelper ClsFileUploadHelper = new ClassFileUploadHelper();

    //查询内容类型
    private string msContentType
    {
        get
        {
            if (LSLIBWebBased.nsSQL.mSQL.oHandleNullAndNothing(this.Request.QueryString["ContenType"]) == null)
            {
                return "Contentype";
            }
            else
            {
                return this.Request.QueryString["ContentType"];
            }
        }
    }

    protected void Page_Init(object sender, EventArgs e)
    {
        //檢查登入權限+取得翻譯表
        LSLIBWebBased.nsClass.mClass.cPageLoadHelper_GuocoWeb(this, ref ClsHashTableHelper, true, "", "", true);
        this.Title = ClsHashTableHelper.sGetHash(ClsHashTableHelper.mClassMyConfiguration.msPostCode);
        this.ucPageHeader1.msTitle = this.Title;
        //this.lblReportName.Text = this.Title;

        LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);

    }

    protected void Page_Load(object sender, EventArgs e)
    {
        // LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);
        //LSLIBWebBased.nsCommon.mCommon.fTextBoxSetEnterEvent(this.txtSearchKey, btnSearch);

        if (!IsPostBack)
        {
            this.divCoverLayer.Visible = false;
            this.divPopUpPanel.Visible = false;

            //this.txtSearchKey.Text = lblInvoiceNum.Text;

            //LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btnExcelUpload_header, "ExcelUpload.aspx?UploadType=TAX_ReconciliationTracking_Header");

            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLSystemCode", ddlSystemCode, LSLIBWebBased.LIBWebBased.enDropDownListType.All);
            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLSystemCode", ddlSystemCode_edit, LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);

            if (ClsHashTableHelper.mClassMyConfiguration.msSystemCode != "")
            {
                ddlSystemCode.SelectedValue = ClsHashTableHelper.mClassMyConfiguration.msSystemCode;
                ddlSystemCode_edit.SelectedValue = ClsHashTableHelper.mClassMyConfiguration.msSystemCode;
                ddlSystemCode.Mode = LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Display;
                ddlSystemCode_edit.Mode = LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Display;
            }
            //LSLIBWebBased.nsCommon.mCommon.BindDDLMaster(this.ddlSystemRights, "2", LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);
            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_Privilege_UserSystemRights_DDLSystemRights", ddlSystemRights, LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);
            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLStatus", ddlInfoStatus_edit, LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);

            FillGridView1();
        }
    }



    private object FillGridView1()
    {

        LSLIBWebBased.ClassLoadFieldHelper ClsLoadFieldHelper = new LSLIBWebBased.ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@SystemCode", this.ddlSystemCode.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Search", this.txtSearchKey.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@ID", "");
        ClsLoadFieldHelper.fAddSqlParameter("@action", "Search");
        ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Privilege_UserSystemRights_GridDetail");
        ClsLoadFieldHelper.fBindControls(GridView1);

        this.lblCountLabel1.Text = (string)ClsLoadFieldHelper.iRowCountDesc();

        LIBLocal.SetViewSQLScript( ClsLoadFieldHelper, this.ClsHashTableHelper, "N", lblPrintSql);

        return null;
    }


    protected void btnSearch_Click(object sender, EventArgs e)
    {
        lblSystemCode.Text = this.ddlSystemCode.Text;
        lblSearch.Text = this.txtSearchKey.Text;

        FillGridView1();
    }

    protected void GridView1_RowDataBound(object sender, System.Web.UI.WebControls.GridViewRowEventArgs e)
    {
        //foreach (GridViewRow row in GridView1.Rows)
        //{
        //    //Button lbtnMarkCloseInfo = (Button)row.FindControl("btnMarkCloseInfo");
        //    //lbtnMarkCloseInfo.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to mark close?") + "');";

        //    Button lbtnResetPassword = (Button)row.FindControl("btnResetPassword");
        //    lbtnResetPassword.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to reset user password?") + "');";

        //    //Button lbtnSendPassword = (Button)row.FindControl("btnSendPassword");
        //    //lbtnSendPassword.OnClientClick = "return confirm('" + ClsHashTableHelper.sGetHash("Are you sure to send user password?") + "');";
        //}
    }


    protected void GridView1_RowCommand(object sender, System.Web.UI.WebControls.GridViewCommandEventArgs e)
    {
        switch (e.CommandName)
        {

            case "Edit1":
                if (this.divCoverLayer.Visible == false)
                {
                    int index1 = Convert.ToInt32(e.CommandArgument);

                    int PageIndex = this.GridView1.PageIndex;
                    int PageSize = this.GridView1.PageSize;

                    index1 = index1 - PageIndex * PageSize;

                    Label lLabel_Edit1 = this.GridView1.Rows[index1].FindControl("lblKey_Header") as Label;
                    string sKey_Edit1 = lLabel_Edit1.Text;

                    //if (bCanHaveRight(sKey_Edit1, "Edit"))
                    {
                        this.Label6.Text = "Edit Rights";
                        this.LbID.Text = "";
                        this.btnUpdate_Info.Text = "Edit";

                        this.divCoverLayer.Visible = true;
                        this.divPopUpPanel.Visible = true;
                        this.div_ProfileStatus_edit.Visible = true;

                        this.txtUserCode.Mode = LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Display;
                        this.ddlSystemCode_edit.Mode = LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Display;

                        ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

                        ClsLoadFieldHelper.fAddSqlParameter("@ID", sKey_Edit1);
                        ClsLoadFieldHelper.fAddSqlParameter("@SystemCode", "");
                        ClsLoadFieldHelper.fAddSqlParameter("@Search", "");
                        ClsLoadFieldHelper.fAddSqlParameter("@action", "Get");
                        ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Privilege_UserSystemRights_GridDetail");

                        ClsLoadFieldHelper.LoadSqlField("UserCode", ref txtUserCode);
                        ClsLoadFieldHelper.LoadSqlField("SystemCode", ref ddlSystemCode_edit);
                        ClsLoadFieldHelper.LoadSqlField("Rights", ref  ddlSystemRights);
                        ClsLoadFieldHelper.LoadSqlField("Status", ref  ddlInfoStatus_edit);
                        ClsLoadFieldHelper.LoadSqlField("ID", ref  LbID);
                        
                    }

                }
                break;

        }
    }


    protected void btnClose_Info_Click(object sender, EventArgs e)
    {
        this.divPopUpPanel.Visible = false;
        this.divCoverLayer.Visible = false;
        this.LbID.Text = "";
        // FillGridView1();
        clearEditFields();
    }

    protected void btnInsert_AddRights_Click(object sender, EventArgs e)
    {
        //this.lblAction.Text = "New";
        //this.txtID.Enabled = true;
        //if (bCanHaveRight("", "Add"))
        {
            this.Label6.Text = "Add Rights";
            this.LbID.Text = "";
            this.btnUpdate_Info.Text = "Add";
            this.div_ProfileStatus_edit.Visible = false;
            this.divPopUpPanel.Visible = true;
            this.divCoverLayer.Visible = true;

            this.txtUserCode.Mode = LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Edit;
            this.txtUserCode.Text = "";

            if (ClsHashTableHelper.mClassMyConfiguration.msSystemCode != "")
            {
                ddlSystemCode_edit.SelectedValue = ClsHashTableHelper.mClassMyConfiguration.msSystemCode;
                ddlSystemCode_edit.Mode = LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Display;
            }
            else
            {
                ddlSystemCode_edit.Mode = LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Edit;
                LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLSystemCode", ddlSystemCode_edit, LSLIBWebBased.LIBWebBased.enDropDownListType.Blank);
            }            
            //this.ddlSystemCode_edit.Enabled = true;
        }
    }


    protected void btnUpdate_Info_Click(object sender, EventArgs e)
    {
        ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@UserName", this.txtUserCode.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@SystemCode", this.ddlSystemCode_edit.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Rights", this.ddlSystemRights.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@UpdateBy", this.ClsHashTableHelper.msUserName);


        if (this.txtUserCode.Mode == LSLIBWebBased.nsWorkFlow.mWorkFlow.Action.Edit)
        {
            ClsLoadFieldHelper.fAddSqlParameter("@Status", "Active");
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Privilege_UserSystemRights_insert");
        }
        else
        {
            ClsLoadFieldHelper.fAddSqlParameter("@Status", this.ddlInfoStatus_edit.Text);
            ClsLoadFieldHelper.fAddSqlParameter("@ID", this.LbID.Text);
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Privilege_UserSystemRights_update");
        }

        if (ClsLoadFieldHelper.mbDataSetHasRecord)
        {
            //LSLIBWebBased.nsScript.mScript.Alert(this, ClsLoadFieldHelper.oLoadSqlField("Result").ToString(), false);
            lblAlert3.Visible = true;
            lblAlert3.Text = ClsLoadFieldHelper.oLoadSqlField("Result").ToString();
        }
        else
        {

            FillGridView1();
            this.divPopUpPanel.Visible = false;
            this.divCoverLayer.Visible = false;
            clearEditFields();
        }
    }


    private object clearEditFields()
    {
     
        //ddlSystemCode_edit.Text = "";
        ddlInfoStatus_edit.Text = "";
        ddlSystemRights.Text = "";
        txtUserCode.Text = "";
        lblAlert3.Visible = false;
        lblAlert3.Text = "";

        return null;
    }

   
}