using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using LSLIBWebBased;
using System.Data;

public partial class View_System : System.Web.UI.Page
{
    protected ClassHashTableHelper ClsHashTableHelper;
    protected ClassFileUploadHelper ClsFileUploadHelper = new ClassFileUploadHelper();

    protected void Page_Init(object sender, EventArgs e)
    {
        //檢查登入權限+取得翻譯表
        LSLIBWebBased.nsClass.mClass.cPageLoadHelper_GuocoWeb(this, ref ClsHashTableHelper, true, "", "", true);
        this.Title = ClsHashTableHelper.sGetHash("View_System") + " - " + ClsHashTableHelper.sGetHash(ClsHashTableHelper.mClassMyConfiguration.msSystemCode);
        this.ucPageHeader1.msTitle = this.Title;

        LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);

        LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btn_GoToConfig_Privilege_UserSystemRights, "Config_Privilege_UserSystemRights.aspx?SystemCode=" + ClsHashTableHelper.mClassMyConfiguration.msSystemCode + "&PostCode=Config_Privilege_UserSystemRights");
        LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btn_GoToConfig_Folder, "Config_Folder.aspx?SystemCode=" + ClsHashTableHelper.mClassMyConfiguration.msSystemCode + "&PostCode=Config_Folder");
        
        //LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btn_AddPost, "View_Post.aspx?SystemCode=" + ClsHashTableHelper.mClassMyConfiguration.msSystemCode);        
        LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btn_AddPost, LIBLocal.sLoadSystemURL(ClsHashTableHelper.mClassMyConfiguration.msSystemCode) 
                                                + "?SystemCode=" + ClsHashTableHelper.mClassMyConfiguration.msSystemCode);

        LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btn_Browse, "Default.aspx?SystemCode=" + ClsHashTableHelper.mClassMyConfiguration.msSystemCode + "&PostCode=Config_Folder");

        //LSLIBWebBased.nsWebControl.mWebControl.SearchWebControl(this.divGridView.Controls, AddressOf fSetControlViewMode)

    }

    protected void Page_Load(object sender, EventArgs e)
    {

        if (!IsPostBack)
        {
            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLSystemTypeCode", ddlSystemTypeCode, LSLIBWebBased.LIBWebBased.enDropDownListType.NoValue);

            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLSystemCode", ddlSystemCode, LSLIBWebBased.LIBWebBased.enDropDownListType.All);
            LSLIBWebBased.nsWebControl.mWebControl.SetControlValue(ClsHashTableHelper.mClassMyConfiguration.msSystemCode, ddlSystemCode);

            LIBLocal2.BindDDLSystemFolder_WithAllChildren(ddlFolderCode, ddlSystemCode.SelectedValue);
            LSLIBWebBased.nsDataSet.mDataSet.BindListControl("stp_wf_all_DDLStatus", ddlStatus, LSLIBWebBased.LIBWebBased.enDropDownListType.All);

            SetControl();
            CheckRight();

            FillGridView1();
        }
    }
    
    protected void SetControl()
    {
        this.trFolder.Visible = true;
        this.trSystem.Visible = true;
        this.trSystemType.Visible = true;
        

        if (ClsHashTableHelper.mClassMyConfiguration.msSystemCode == "All")
        {
            this.trFolder.Visible = false;
            this.trSystem.Visible = false;

            LSLIBWebBased.nsWebControl.mWebControl.SetControlValue(ClsHashTableHelper.mClassMyConfiguration.msSystemTypeCode, ddlSystemTypeCode);
            LSLIBWebBased.nsWebControl.mWebControl.SetControlValue("Pending", ddlStatus);

            this.ddlSystemTypeCode.Mode = LSLIBWebBased.nsWebControl.mWebControl.ModeDisplay();
            this.ddlSystemCode.Mode = LSLIBWebBased.nsWebControl.mWebControl.ModeDisplay();
            this.ddlStatus.Mode = LSLIBWebBased.nsWebControl.mWebControl.ModeDisplay();
        }
        else
        {
            LSLIBWebBased.nsWebControl.mWebControl.SetControlValue( LIBLocal.sLoadSystemTypeCode(this.ddlSystemCode.SelectedValue), ddlSystemTypeCode);
            
            this.trSystemType.Visible = false;
            LSLIBWebBased.nsWebControl.mWebControl.SetControlValue("Active", ddlStatus);

            this.ddlSystemCode.Mode = LSLIBWebBased.nsWebControl.mWebControl.ModeDisplay();
            //this.ddlStatus.Mode = LSLIBWebBased.nsWebControl.mWebControl.ModeDisplay();

        }
    }
    protected void CheckRight()
    {
        if (LIBLocal.bCanHaveRight(this.ClsHashTableHelper.msUserName
                              , ClsHashTableHelper.mClassMyConfiguration.msSystemCode
                              , ClsHashTableHelper.mClassMyConfiguration.msFolderCode
                              , ClsHashTableHelper.mClassMyConfiguration.msPostCode
                              , "Create") == true)
        {
            btn_AddPost.Visible = true;
        }
        else
        {
            btn_AddPost.Visible = false;
        }

        if (LIBLocal.bCanHaveRight(this.ClsHashTableHelper.msUserName
                              , this.ClsHashTableHelper.mClassMyConfiguration.msSystemCode
                              , this.ClsHashTableHelper.mClassMyConfiguration.msFolderCode
                              , this.ClsHashTableHelper.mClassMyConfiguration.msPostCode
                              , "Administrator") == true)
        {
            btn_GoToConfig_Privilege_UserSystemRights.Visible = true;
            btn_GoToConfig_Folder.Visible = true;
        }
        else
        {
            btn_GoToConfig_Privilege_UserSystemRights.Visible = false;
            btn_GoToConfig_Folder.Visible = false;
        }
    }
    
    private object FillGridView1()
    {

        this.lblReportName.Text = this.ddlFolderCode.SelectedItem.Text;
        LSLIBWebBased.ClassLoadFieldHelper ClsLoadFieldHelper = new LSLIBWebBased.ClassLoadFieldHelper();
        ClsLoadFieldHelper.fAddSqlParameter("@UserCode", this.ClsHashTableHelper.msUserName);
        ClsLoadFieldHelper.fAddSqlParameter("@SystemTypeCode", this.ddlSystemTypeCode.SelectedValue);
        ClsLoadFieldHelper.fAddSqlParameter("@SystemCode", this.ddlSystemCode.SelectedValue);
        ClsLoadFieldHelper.fAddSqlParameter("@FolderCode", this.ddlFolderCode.SelectedValue);
        ClsLoadFieldHelper.fAddSqlParameter("@Status", this.ddlStatus.SelectedValue);
        ClsLoadFieldHelper.fAddSqlParameter("@SearchKey", this.txtSearchKey);
        ClsLoadFieldHelper.fBuildDataSet("stp_wf_dms_Grid_ViewSystem");
        ClsLoadFieldHelper.fBindControls(GridView1);
        this.lblCountLabel1.Text = (string)ClsLoadFieldHelper.iRowCountDesc();

        LIBLocal.SetViewSQLScript( ClsLoadFieldHelper, this.ClsHashTableHelper, "N", lblPrintSql);

        return null;
    }
    
    protected void ddlFolderCode_SelectedIndexChanged(object sender, EventArgs e)
    {
        FillGridView1();
    }

    protected void ddlSystemTypeCode_SelectedIndexChanged(object sender, EventArgs e)
    {

    }
    protected void ddlSystemCode_SelectedIndexChanged(object sender, EventArgs e)
    {
        LIBLocal2.BindDDLSystemFolder_WithAllChildren(ddlFolderCode, ddlSystemCode.SelectedValue);
        FillGridView1();
    }

    protected void btnSearch_Click(object sender, EventArgs e)
    {
        FillGridView1();

    }

    protected void GridView1_RowDataBound(object sender, GridViewRowEventArgs e)
    {
        if (e.Row.Cells.Count > 0)
        {

            if (e.Row.RowType == DataControlRowType.DataRow || e.Row.RowType == DataControlRowType.Header)
            {
                e.Row.Cells[e.Row.Cells.Count - 3].Visible = false;
                e.Row.Cells[e.Row.Cells.Count - 2].Visible = false;
                e.Row.Cells[e.Row.Cells.Count - 1].Visible = false;
            }
        }
    }



}