using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using LSLIBWebBased;
using System.Data;


public partial class WF_DDLField : System.Web.UI.Page
{

    protected ClassHashTableHelper ClsHashTableHelper;
    protected ClassFileUploadHelper ClsFileUploadHelper = new ClassFileUploadHelper();
    
    protected void Page_Init(object sender, EventArgs e)
    {
        //檢查登入權限+取得翻譯表
        LSLIBWebBased.nsClass.mClass.cPageLoadHelper_GuocoWeb(this, ref ClsHashTableHelper, true, "", "", true);
        this.Title = ClsHashTableHelper.sGetHash(ClsHashTableHelper.mClassMyConfiguration.msPostCode);
        this.ucPageHeader1.msTitle = this.Title;

        LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);

    }

    protected void Page_Load(object sender, EventArgs e)
    {

        //ScriptManager.RegisterClientScriptBlock(this, this.GetType(), "anything", "test();", true);
        LSLIBWebBased.nsClass.mClass.cGridViewAddSortMethod(this.GridView1, FillGridView1, this.lblSortLabel1, null, ClassGridViewHelper.enGridViewTypeCollection.DetailReportWithAutoGeneratedColumnWithNoHeader);
         LSLIBWebBased.nsCommon.mCommon.fTextBoxSetEnterEvent(this.txtSearchKey, btnSearch);

        if (!IsPostBack)
        {
            this.divPopUpPanel.Visible = false;
            this.divCoverLayer.Visible = false;
            this.txtSeq_No.Enabled = false;
           
            //this.txtSearchKey.Text = lblInvoiceNum.Text;
                        
            //LSLIBWebBased.nsCommon.mCommon.fButtonSetOpenURL(this.btnExcelUpload_header, "ExcelUpload.aspx?UploadType=TAX_ReconciliationTracking_Header");
          
            FillGridViewAll();
                       
        }
    }


    private object FillGridViewAll()
    {
        FillGridView1();

        return null;
    }

    private object FillGridView1()
    {

        LSLIBWebBased.ClassLoadFieldHelper ClsLoadFieldHelper = new LSLIBWebBased.ClassLoadFieldHelper();

        ClsLoadFieldHelper.fAddSqlParameter("@Search", this.txtSearchKey);
        ClsLoadFieldHelper.fAddSqlParameter("@action", "Search");
        ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Field_GridDetail");
        ClsLoadFieldHelper.fBindControls(GridView1);

        this.lblCountLabel1.Text = (string)ClsLoadFieldHelper.iRowCountDesc();
        LIBLocal.SetViewSQLScript(ClsLoadFieldHelper, this.ClsHashTableHelper, "N", lblPrintSql);

        return null;
    }

    
   
    protected void btnSearch_Click(object sender, EventArgs e)
    {
        FillGridViewAll();
    }


    protected void GridView1_RowCommand(object sender, System.Web.UI.WebControls.GridViewCommandEventArgs e)
    {

        switch (e.CommandName)
        {
            
            case "Edit1":
                if (this.divCoverLayer.Visible == false)
                {
                    int index1 = Convert.ToInt32(e.CommandArgument);

                    int PageIndex = this.GridView1.PageIndex;
                    int PageSize = this.GridView1.PageSize;

                    index1 = index1 - PageIndex * PageSize;

                    this.Label9.Text = "更新-tbl_wf_all_Field";
                    this.divPopUpPanel.Visible = true;
                    this.divCoverLayer.Visible = true;
                    this.btnGetNewField_Type.Visible = false;


                    Label lLabel_Edit1 = this.GridView1.Rows[index1].FindControl("lblKey_Header") as Label;
                    string sKey_Edit1 = lLabel_Edit1.Text;

                    ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

                    ClsLoadFieldHelper.fAddSqlParameter("@Search", sKey_Edit1);
                    ClsLoadFieldHelper.fAddSqlParameter("@action", "Get");
                    ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Field_GridDetail");

                    this.txtSeq_No.Text = sKey_Edit1;
                    //this.txtSeq_No.Enabled = false;
                    ClsLoadFieldHelper.LoadSqlField("Field_en", ref txtField_en);
                    ClsLoadFieldHelper.LoadSqlField("Field_tc", ref txtField_tc);
                    ClsLoadFieldHelper.LoadSqlField("Field_sc", ref txtField_sc);
                    ClsLoadFieldHelper.LoadSqlField("Field_Type", ref txtField_Type);
                    ClsLoadFieldHelper.LoadSqlField("Sort_Seq", ref txtSort_Seq);
                    ClsLoadFieldHelper.LoadSqlField("Field_Key", ref txtKey);

                }
                break;

            case "Copy1":
                if (this.divCoverLayer.Visible == false)
                {
                    int index1 = Convert.ToInt32(e.CommandArgument);

                    int PageIndex = this.GridView1.PageIndex;
                    int PageSize = this.GridView1.PageSize;

                    index1 = index1 - PageIndex * PageSize;

                    this.Label9.Text = "複製及新增-tbl_wf_all_Field";
                    this.divPopUpPanel.Visible = true;
                    this.divCoverLayer.Visible = true;
                    this.btnGetNewField_Type.Visible = false;


                    Label lLabel_Edit1 = this.GridView1.Rows[index1].FindControl("lblKey_Header") as Label;
                    string sKey_Edit1 = lLabel_Edit1.Text;

                    ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

                    ClsLoadFieldHelper.fAddSqlParameter("@Search", sKey_Edit1);
                    ClsLoadFieldHelper.fAddSqlParameter("@action", "Get");
                    ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Field_GridDetail");

                    this.txtSeq_No.Text = "";
                    ClsLoadFieldHelper.LoadSqlField("Field_en", ref txtField_en);
                    ClsLoadFieldHelper.LoadSqlField("Field_tc", ref txtField_tc);
                    ClsLoadFieldHelper.LoadSqlField("Field_sc", ref txtField_sc);
                    ClsLoadFieldHelper.LoadSqlField("Field_Type", ref txtField_Type);
                    ClsLoadFieldHelper.LoadSqlField("Sort_Seq", ref txtSort_Seq);
                    ClsLoadFieldHelper.LoadSqlField("Field_Key", ref txtKey);

                }
                break;
        }
    }

    protected void btnCloseEditHeader_Click(object sender, EventArgs e)
    {
        this.divPopUpPanel.Visible = false;
        this.divCoverLayer.Visible = false;
        clearEditHeaderFields();
    }

    protected void btnInsert_Click(object sender, EventArgs e)
    {
        this.Label9.Text = "新增-tbl_wf_all_Field";
        this.txtKey.Enabled = true;
        this.divPopUpPanel.Visible = true;
        this.divCoverLayer.Visible = true;
        this.btnGetNewField_Type.Visible = true;
    }

    protected void btnUpdateEditHeader_Click(object sender, EventArgs e)
    {

        ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();
        
        ClsLoadFieldHelper.fAddSqlParameter("@Seq_No", txtSeq_No.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Field_Key", txtKey.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Field_en", txtField_en.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Field_tc", txtField_tc.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Field_sc", txtField_sc.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Field_Type", txtField_Type.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@Sort_Seq", txtSort_Seq.Text);
        ClsLoadFieldHelper.fAddSqlParameter("@UpdateBy", this.ClsHashTableHelper.msUserName);

        if (txtSeq_No.Text != "")
        {
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Field_Update");
        }
        else
        {
            ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Field_insert");
        }

       
        if (ClsLoadFieldHelper.mbDataSetHasRecord)
        {
            lblAlert1.Visible = true;
            lblAlert1.Text = ClsLoadFieldHelper.oLoadSqlField("Result").ToString();
        }
        else
        {
            //FillGridView2();

            FillGridView1();

            this.divPopUpPanel.Visible = false;
            this.divCoverLayer.Visible = false;
            clearEditHeaderFields();
        }
    }

    protected void btnGetNewField_Type_Click(object sender, EventArgs e)
    {

        ClassLoadFieldHelper ClsLoadFieldHelper = new ClassLoadFieldHelper();

        ClsLoadFieldHelper.fBuildDataSet("stp_wf_all_Field_GetNewField_Type");

        this.txtField_Type.Text = ClsLoadFieldHelper.oLoadSqlField("Field_Type").ToString();
    }


    private object clearEditHeaderFields()
    {
        txtSeq_No.Text = "";
        txtKey.Text = "";
        txtField_en.Text = "";
        txtField_tc.Text = "";
        txtField_sc.Text = "";
        txtField_Type.Text = "";
        txtSort_Seq.Text = "";
        lblAlert1.Visible = false;
        lblAlert1.Text = "";

        return null;
    }


   
   

}